### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by codeinabox**
Add limitations based on experience of the payments team

### CODE REVIEW

**Comment by bobthemighty** [comment]
Thanks for the feedback!

I'm _not_ intending to merge this PR, because the first point - that the library requires typescript compiler flags to be set - is already documented: https://github.com/cazoo-engineering/ssmble#configuring-the-typescript-compiler

The second point should be treated as a bug and fixed - could you give me a reproduction? I don't think we should just add a line to the readme to say "meh, maybe it won't work for you and you'll have to do something different".

**Comment by codeinabox** [comment]
Sure, our parameters are structured into separate folders a bit like this

Assuming the following parameters stored in SSM:

```
/payments
   /stripe
      /email-blocklist-id
      /email-flaglist-id 
   /truelayer
     /root-domain
     /client-id
```

We'd like to call `getConfig` and have this tree structure returned as an object a bit like this

```ts
import {store, param, Is, getConfig} from 'ssmble'

// the `store` decorator binds this class to an SSM hierarchy

@store('/payments')
class PaymentsConfiguration {

  // the `param` decorator binds a class property to an SSM parameter

  @param()
  stripe: {
      emailBlocklistId: string
      emailFlaglistId: string 
  }
  
  @param()
  truelayer: {
      rootDomain: string
      clientId: string 
  }
}
```

**Comment by bobthemighty** [comment]
Hi @codeinabox I've spent some time playing around, the trouble is that Typescript decorators only apply to classes, and class definitions aren't easily nested. I could definitely make this work:

```
class Stripe { 
  @param()
  emailBlockListId: string
  }
  
  class TrueLayer {
    @param()
    clientId: string
  }
  
  @store(...)
  class Config{
     stripe: Stripe
     truelayer: TrueLayer
  }
```

But that _sucks_ so I'm not going to. Instead I think I'm going to take some time this weekend and try a different approach. I previously wrote a library that works like this, but against consul https://github.com/bobthemighty/12factorial

That works by taking an object literal that describes the shape of the config. In your example, it might look like this:

```
const cfg = {
   stripe: {
      emailBlockListId: param<string>()
      emailflagListId: param<string>()
   }

   truelayer: {
      clientId: param<string>()
   }
}
```

The tricky part is making that type safe, which is why I went with the class decorator approach before, but I've got some initial thoughts on how that might work.

**Comment by bobthemighty** [comment]
@codeinabox I think this PR is deprecated by #16 

Can you check that you're happy with the contents of that PR, now published as version 0.8.0, so that I can close this?

**Pull request closed without merging**
